spring.application.name=entreprise

# Port d'execution du microservice Entreprise
# 8080 est deja occupe par Jenkins sur cette machine -> on utilise 9090
server.port=9090

# Ne pas recreer la base a chaque demarrage
spring.jpa.hibernate.ddl-auto=update

# Base H2 fichier dediee au microservice Entreprise
spring.datasource.url=jdbc:h2:file:./entreprise
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console H2 : http://localhost:9090/h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# Emplacement du microservice Employe (appel REST inter-services)
employe.service.url=http://localhost:8081/api
